server:
  port: 8000

spring:
  # application 정보 설정
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: chat-server
          uri: lb://CHAT-SERVER
          predicates:
            - Path=/chat-server/**
        - id: song-server
          uri: lb://SONG-SERVER
          predicates:
            - Path=/song-server/**
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/user-server/**
        - id: userservice-server
          uri: lb://USERSERVICE-SERVER
          predicates:
            - Path=/userservice-server/**

# eureka 설정
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.9.0.2:8761/eureka


